"""
Exhaustive exempt-artifact catalog for governance policy regression tests.

Each entry is ``(category, relative_path)``. Paths are repo-agnostic unless noted.
"""

from __future__ import annotations

# fmt: off
COMPLETE_EXEMPT_CATALOG: list[tuple[str, str]] = [
    # ── Documentation & legal ──
    ("docs", "README.md"),
    ("docs", "Readme.md"),
    ("docs", "CHANGELOG.md"),
    ("docs", "CONTRIBUTING.md"),
    ("docs", "SECURITY.md"),
    ("docs", "CODE_OF_CONDUCT.md"),
    ("docs", "docs/index.md"),
    ("docs", "docs/api/v2/reference.mdx"),
    ("docs", "docs/reports/benchmark-results.md"),
    ("docs", "website/blog/2024/release.md"),
    ("docs", ".cursor/rules/hermes.mdc"),
    ("docs", "NOTES.txt"),
    ("docs", "AUTHORS"),
    ("docs", "COPYING"),
    ("docs", "LICENSE"),
    ("docs", "CODEOWNERS"),
    ("docs", "legal/third-party-notices.txt"),
    ("docs", "wiki/Home.adoc"),
    ("docs", "guide.org"),
    # ── Node / JS manifests ──
    ("package", "package.json"),
    ("package", "Package.json"),
    ("package", "package-lock.json"),
    ("package", "pnpm-lock.yaml"),
    ("package", "yarn.lock"),
    ("package", "bun.lockb"),
    ("package", "bun.lock"),
    ("package", "npm-shrinkwrap.json"),
    ("package", "pnpm-workspace.yaml"),
    ("package", "lerna.json"),
    ("package", "nx.json"),
    ("package", "turbo.json"),
    ("package", "rush.json"),
    ("package", "workspace.json"),
    ("package", "manifest.json"),
    ("package", "site.webmanifest"),
    ("package", "renovate.json"),
    ("package", "dependabot.yml"),
    ("package", ".snyk"),
    # ── Python / Rust / Go / JVM / Ruby / PHP / Elixir ──
    ("package", "pyproject.toml"),
    ("package", "setup.py"),
    ("package", "setup.cfg"),
    ("package", "requirements.txt"),
    ("package", "requirements-dev.txt"),
    ("package", "Pipfile"),
    ("package", "Pipfile.lock"),
    ("package", "poetry.lock"),
    ("package", "uv.lock"),
    ("package", "Cargo.toml"),
    ("package", "Cargo.lock"),
    ("package", "go.mod"),
    ("package", "go.sum"),
    ("package", "build.gradle"),
    ("package", "settings.gradle"),
    ("package", "gradle.properties"),
    ("package", "pom.xml"),
    ("package", "build.xml"),
    ("package", "Gemfile"),
    ("package", "Gemfile.lock"),
    ("package", "composer.json"),
    ("package", "composer.lock"),
    ("package", "mix.exs"),
    ("package", "mix.lock"),
    ("package", "rebar.config"),
    ("package", "stack.yaml"),
    ("package", "cabal.project"),
    ("package", "Package.swift"),
    ("package", "Cartfile"),
    ("package", "Podfile"),
    ("package", "Podfile.lock"),
    # ── Toolchain / lint / format configs ──
    ("config", "tsconfig.json"),
    ("config", "tsconfig.build.json"),
    ("config", "jsconfig.json"),
    ("config", "biome.json"),
    ("config", "knip.json"),
    ("config", "typedoc.json"),
    ("config", "jsdoc.json"),
    ("config", ".prettierrc"),
    ("config", ".prettierrc.json"),
    ("config", ".eslintrc"),
    ("config", ".eslintrc.cjs"),
    ("config", ".babelrc"),
    ("config", ".stylelintrc"),
    ("config", ".editorconfig"),
    ("config", ".browserslistrc"),
    ("config", "vite.config.ts"),
    ("config", "vitest.config.ts"),
    ("config", "vitest.workspace.ts"),
    ("config", "jest.config.js"),
    ("config", "jest.config.ts"),
    ("config", "webpack.config.js"),
    ("config", "rollup.config.js"),
    ("config", "rollup.config.mjs"),
    ("config", "next.config.mjs"),
    ("config", "nuxt.config.ts"),
    ("config", "eslint.config.mjs"),
    ("config", "postcss.config.cjs"),
    ("config", "tailwind.config.ts"),
    ("config", "playwright.config.ts"),
    ("config", "cypress.config.ts"),
    ("config", "stryker.config.js"),
    ("config", "drizzle.config.ts"),
    ("config", "orval.config.ts"),
    ("config", "openapi-ts.config.ts"),
    ("config", "components.json"),
    ("config", "mise.toml"),
    ("config", "flake.nix"),
    ("config", "shell.nix"),
    ("config", "buf.yaml"),
    ("config", "buf.gen.yaml"),
    ("config", "redocly.yaml"),
    ("config", "spectral.yaml"),
    ("config", "graphql.config.yml"),
    ("config", "apollo.config.js"),
    ("config", "deno.json"),
    ("config", "deno.jsonc"),
    ("config", "wrangler.toml"),
    ("config", "bunfig.toml"),
    ("config", "moon.yml"),
    # ── Database / ORM / migrations ──
    ("database", "prisma/schema.prisma"),
    ("database", "prisma/migrations/20240101_init/migration.sql"),
    ("database", "drizzle/meta/_journal.json"),
    ("database", "db/migrations/001_users.sql"),
    ("database", "supabase/migrations/20240101_remote.sql"),
    ("database", "hasura/metadata/databases.yaml"),
    ("database", "typeorm/migrations/1234-AddUser.ts"),
    ("database", "sequelize/migrations/2020-create-user.js"),
    ("database", "knex/migrations/20240101_users.js"),
    ("database", "alembic/versions/001_init.py"),
    ("database", "flyway/sql/V1__init.sql"),
    ("database", "liquibase/changelog.xml"),
    ("database", "schema.dbml"),
    ("database", "dump.sqlite"),
    ("database", "dev.db"),
    ("database", "seeders/users.sql"),
    ("database", "seeds/dev.rb"),
    ("database", "sql/reporting/views.sql"),
    # ── Docker / containers ──
    ("container", "Dockerfile"),
    ("container", "dockerfile"),
    ("container", "Dockerfile.prod"),
    ("container", "Containerfile"),
    ("container", "docker-compose.yml"),
    ("container", "docker-compose.override.yaml"),
    ("container", "compose.yaml"),
    ("container", "earthfile"),
    ("container", "Makefile"),
    ("container", "justfile"),
    # ── CI / CD / hooks ──
    ("ci", ".github/workflows/ci.yml"),
    ("ci", ".github/workflows/release.yaml"),
    ("ci", ".github/dependabot.yml"),
    ("ci", ".github/PULL_REQUEST_TEMPLATE.md"),
    ("ci", ".gitlab-ci.yml"),
    ("ci", ".circleci/config.yml"),
    ("ci", ".travis.yml"),
    ("ci", ".buildkite/pipeline.yml"),
    ("ci", ".husky/pre-commit"),
    ("ci", "Jenkinsfile"),
    ("ci", "azure-pipelines.yml"),
    ("ci", "bitbucket-pipelines.yml"),
    ("ci", "cloudbuild.yaml"),
    ("ci", "appveyor.yml"),
    ("ci", "codecov.yml"),
    ("ci", ".pre-commit-config.yaml"),
    # ── Cloud / PaaS / IaC ──
    ("cloud", "vercel.json"),
    ("cloud", "netlify.toml"),
    ("cloud", "firebase.json"),
    ("cloud", "serverless.yml"),
    ("cloud", "template.yaml"),
    ("cloud", "sam.template.yaml"),
    ("cloud", "fly.toml"),
    ("cloud", "render.yaml"),
    ("cloud", "railway.toml"),
    ("cloud", "pulumi/Pulumi.yaml"),
    ("cloud", "skaffold.yaml"),
    ("cloud", "tiltfile"),
    ("cloud", "terraform/main.tf"),
    ("cloud", "terraform/variables.tfvars"),
    ("cloud", "cdktf/cdktf.json"),
    ("cloud", "ansible/playbook.yml"),
    ("cloud", "k8s/deployment.yaml"),
    ("cloud", "helm/Chart.yaml"),
    ("cloud", "charts/app/values.yaml"),
    ("cloud", "deploy/kustomization.yaml"),
    ("cloud", "policy/auth.rego"),
    ("cloud", "nomad/job.hcl"),
    ("cloud", "infra/main.bicep"),
    # ── Env / secrets ──
    ("env", ".env"),
    ("env", ".env.local"),
    ("env", ".env.development"),
    ("env", ".env.production"),
    ("env", ".env.test"),
    ("env", ".env.example"),
    ("env", ".env.sample"),
    # ── Web / markup / styles ──
    ("web", "index.html"),
    ("web", "public/index.html"),
    ("web", "templates/base.html"),
    ("web", "styles/main.css"),
    ("web", "styles/theme.scss"),
    ("web", "App.vue"),
    ("web", "Button.svelte"),
    ("web", "pages/index.astro"),
    ("web", "views/layout.blade.php"),
    # ── API / contracts / proto ──
    ("api", "openapi/openapi.yaml"),
    ("api", "swagger/swagger.json"),
    ("api", "postman/collection.json"),
    ("api", "proto/user/v1/user.proto"),
    ("api", "protos/events/order.proto"),
    ("api", "contracts/openapi/v3/api.yaml"),
    ("api", "schemas/json/user.schema.json"),
    ("api", "json-schema/product.json"),
    ("api", "schema.graphql"),
    ("api", "service.proto"),
    ("api", "api.avdl"),
    # ── i18n ──
    ("i18n", "locales/en/messages.po"),
    ("i18n", "translations/en.json"),
    ("i18n", "i18n/en.yaml"),
    # ── Test / story / declaration artifacts ──
    ("test", "src/foo.test.ts"),
    ("test", "src/foo.spec.tsx"),
    ("test", "src/__tests__/bar.test.js"),
    ("test", "src/__mocks__/fs.ts"),
    ("test", "src/ui/Button.stories.tsx"),
    ("test", "src/types/global.d.ts"),
    ("test", "src/types/env.d.ts"),
    ("test", "e2e/login.cy.ts"),
    ("test", "e2e/checkout.spec.ts"),
    ("test", "tests/api.integration.ts"),
    ("test", "tests/deploy.smoke.ts"),
    ("test", "pact/consumer.contract.ts"),
    ("test", "mocks/handlers.ts"),
    ("test", "stubs/logger.ts"),
    ("test", "test-utils/render.tsx"),
    ("test", "fixtures/users.json"),
    ("test", "__snapshots__/App.test.tsx.snap"),
    ("test", "golden/output.json"),
    ("test", "testdata/input.csv"),
    ("test", "__fixtures__/order.json"),
    # ── Build / vendor / cache ──
    ("vendor", "node_modules/react/index.js"),
    ("vendor", "node_modules/@types/node/index.d.ts"),
    ("vendor", "dist/bundle.js"),
    ("vendor", "dist/chunk.min.js"),
    ("vendor", "build/output.js"),
    ("vendor", "out/release/main.js"),
    ("vendor", "target/debug/build.js"),
    ("vendor", ".next/static/chunks/main.js"),
    ("vendor", ".nuxt/dist/client.js"),
    ("vendor", ".svelte-kit/output/client.js"),
    ("vendor", "coverage/lcov.info"),
    ("vendor", "coverage/coverage-final.json"),
    ("vendor", ".turbo/cache/meta.json"),
    ("vendor", ".cache/vite/deps/_metadata.json"),
    ("vendor", ".pnpm-store/v10/files/00/pkg.json"),
    ("vendor", "vendor/bundle.js"),
    ("vendor", "third_party/lib.js"),
    ("vendor", "generated/client.ts"),
    ("vendor", "__generated__/types.ts"),
    # ── Storybook / e2e tooling dirs ──
    ("tooling", ".storybook/main.ts"),
    ("tooling", ".storybook/preview.tsx"),
    ("tooling", "storybook-static/index.json"),
    ("tooling", "cypress/e2e/login.ts"),
    ("tooling", "playwright/fixtures.ts"),
    ("tooling", "benchmarks/throughput.bench.ts"),
    # ── Docs / site trees (segment prefixes) ──
    ("docs_tree", "docs/guide/install.md"),
    ("docs_tree", "documentation/api.md"),
    ("docs_tree", "reports/q4-summary.md"),
    ("docs_tree", "website/docusaurus.config.js"),
    ("docs_tree", "blog/post.mdx"),
  # ── Mobile ──
    ("mobile", "pubspec.yaml"),
    ("mobile", "android/app/build.gradle"),
    ("mobile", "android/app/google-services.json"),
    ("mobile", "ios/Runner/Info.plist"),
    ("mobile", "capacitor.config.ts"),
    ("mobile", "eas.json"),
    # ── Security / compliance ──
    ("security", "sbom.json"),
    ("security", "sbom.spdx.json"),
    ("security", "cyclonedx.json"),
    ("security", "security.txt"),
    ("security", "osv-scanner.toml"),
    ("security", "grype.yaml"),
    ("security", "trivy.yaml"),
    # ── Observability ──
    ("ops", "grafana/dashboards/api.json"),
    ("ops", "prometheus/alerts.yml"),
    ("ops", "alertmanager/config.yml"),
    ("ops", "datadog/monitors.yaml"),
    # ── Design / CMS ──
    ("design", "design-tokens/colors.json"),
    ("design", "design/icons.svg"),
    ("design", "cms/sanity.config.ts"),
    ("design", "cms/sanity/schema.ts"),
    # ── Assets / media / certs ──
    ("asset", "public/logo.png"),
    ("asset", "static/hero.webp"),
    ("asset", "media/intro.avif"),
    ("asset", "fonts/inter.woff2"),
    ("asset", "certs/server.pem"),
    ("asset", "archive/release.tar.gz"),
    ("asset", "bundle.wasm"),
    # ── Other languages (non-TS/JS source) ──
    ("lang", "main.py"),
    ("lang", "lib/helper.go"),
    ("lang", "src/lib.rs"),
    ("lang", "App.java"),
    ("lang", "Program.cs"),
    ("lang", "lib/service.ex"),
    ("lang", "lib/main.nim"),
    ("lang", "src/app.zig"),
    ("lang", "app/Main.dart"),
    ("lang", "scripts/deploy.sh"),
    ("lang", "Makefile.win"),
    # ── IDE / assistant ──
    ("ide", ".vscode/settings.json"),
    ("ide", ".vscode/extensions.json"),
    ("ide", ".idea/workspace.xml"),
    ("ide", ".cursor/rules"),
    ("ide", ".cursorindexingignore"),
    ("ide", "copilot-instructions.md"),
    ("ide", ".windsurfrules"),
    ("ide", ".aiderignore"),
    # ── Hermes / agent repo patterns ──
    ("hermes", "AGENTS.md"),
    ("hermes", "CLAUDE.md"),
    ("hermes", "optional-skills/github/foo/SKILL.md"),
    ("hermes", "skills/github/deploy/SKILL.md"),
    ("hermes", "pyproject.toml"),
    ("hermes", "herm-tui/package.json"),
    ("hermes", "website/package.json"),
    # ── User-reported false positives (TypingJoy-style) ──
    ("reported", "/Users/dev/Desktop/TypingJoy/package.json"),
    ("reported", "/Users/dev/Desktop/TypingJoy/README.md"),
    ("reported", "/Users/dev/Desktop/TypingJoy/docs/reports/benchmark.md"),
    ("reported", "C:\\Users\\dev\\TypingJoy\\package.json"),
    # ── Lockfile / rc heuristics ──
    ("heuristic", "packages/api/custom.lock"),
    ("heuristic", "tools/foo-lock.json"),
    ("heuristic", "biome.rc.yaml"),
    # ── Compound extensions ──
    ("compound", "dist/app.min.js"),
    ("compound", "styles/app.min.css"),
    ("compound", "release/app.bundle.js"),
    ("compound", "archives/backup.tar.gz"),
    ("compound", "archives/data.tar.bz2"),
    # ── v9: Hermes / monorepo real-world paths ──
    ("hermes_v9", ".envrc"),
    ("hermes_v9", ".env.example"),
    ("hermes_v9", "MANIFEST.in"),
    ("hermes_v9", ".mailmap"),
    ("hermes_v9", "Dockerfile.operator-api"),
    ("hermes_v9", "RELEASE_v0.14.0.md"),
    ("hermes_v9", ".plans/openai-api-server.md"),
    ("hermes_v9", "acp_registry/agent.json"),
    ("hermes_v9", "assets/banner.png"),
    ("hermes_v9", ".github/FUNDING.yml"),
    ("hermes_v9", ".github/ISSUE_TEMPLATE/bug_report.yml"),
    ("hermes_v9", ".github/actions/nix-setup/action.yml"),
    ("hermes_v9", "README.zh-CN.md"),
    ("hermes_v9", "dprint.json"),
    ("hermes_v9", "tsup.config.ts"),
    ("hermes_v9", ".devcontainer/devcontainer.json"),
    ("hermes_v9", "constraints.txt"),
    ("hermes_v9", "environment.yml"),
    # ── v9: build systems ──
    ("buildsys", "WORKSPACE"),
    ("buildsys", "BUILD"),
    ("buildsys", "meson.build"),
    ("buildsys", "meson_options.txt"),
    ("buildsys", "GNUmakefile"),
    ("buildsys", "Makefile.am"),
    # ── v9: edge env / config ──
    ("env", ".envrc"),
    ("env", "env.development"),
    ("config", "ladle.config.ts"),
    ("config", "semantic-release.config.js"),
    ("config", ".commitlintrc.js"),
    # ── v9: subtitles / data ──
    ("data", "captions/en.vtt"),
    ("data", "inbox/message.eml"),
    ("data", "export/report.parquet"),
    # ── v10: Hermes repo gaps (git ls-files audit) ──
    ("hermes_v10", ".venv"),
    ("hermes_v10", "hermes"),
    ("hermes_v10", "scripts/hermes-gateway"),
    ("hermes_v10", "broccolidb/.broccolidb/paste_store/cc/abc123"),
    ("hermes_v10", "herm-tui/assets/eikons/default.eikon"),
    ("hermes_v10", "herm-tui/bin/herm.cjs"),
    ("hermes_v10", "plugins/kanban/systemd/hermes-kanban-dispatcher.service"),
    ("hermes_v10", "skills/research/research-paper-writing/templates/acl/acl_latex.tex"),
    ("hermes_v10", "skills/research/research-paper-writing/templates/acl/acl.sty"),
    ("hermes_v10", "skills/research/research-paper-writing/templates/acl/custom.bib"),
    ("hermes_v10", "scripts/whatsapp-bridge/allowlist.test.mjs"),
    ("hermes_v10", "broccolidb/tests/benchmark.ts"),
    ("hermes_v10", "broccolidb/tests/stress.ts"),
]

# Paths that must stay governable (anti-regression for over-broad rules).
MUST_REMAIN_GOVERNABLE_CATALOG: list[str] = [
    "src/domain/User.ts",
    "src/domain/model/Order.ts",
    "src/core/AppController.ts",
    "src/application/CreateOrderUseCase.ts",
    "src/infrastructure/persistence/UserRepository.ts",
    "src/ui/components/Button.tsx",
    "src/ui/hooks/useAuth.ts",
    "src/lib/utils/format.js",
    "src/workflows/runner.ts",
    "src/skills/SkillRegistry.ts",
    "src/graphql/resolvers/Query.ts",
    "src/content/models/Article.ts",
    "src/schema/validation/rules.ts",
    "src/contracts/domain/Agreement.ts",
    "src/testing/builders/UserBuilder.ts",
    "src/modules/payments/CheckoutService.ts",
    "packages/core/src/index.ts",
    "packages/api/src/handler.ts",
    "apps/web/src/main.tsx",
    "lib/shared/constants.js",
    "server/routes/health.ts",
    "src/domain/entities/Order.ts",
    "src/examples/demo/Widget.ts",
    "src/assets/IconRegistry.ts",
    "src/public/ApiHandler.ts",
    "src/static/bundler.ts",
    "src/design/system/Token.ts",
    "src/orm/EntityMapper.ts",
    "src/gen/codegen.ts",
]
# fmt: on
